export const permissions = {
  dashboard: "dashboard",
  products: "products",
  batchView: "batchView",
  batchCreate: "batchCreate",
  batchEdit: "batchEdit",
  batchDelete: "batchDelete",
  parties: "parties",
  partiesExport: "partiesExport",
  stockInView: "stockInView",
  stockInCreate: "stockInCreate",
  stockOutView: "stockOutView",
  stockOutCreate: "stockOutCreate",
  ledger: "ledger",
  reports: "reports",
  expiryAlerts: "expiryAlerts",
  users: "users",
  settings: "settings",
  backupExport: "backupExport",
} as const;
