"use client";

import { useEffect } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import {
  Alert,
  Button,
  Card,
  CardContent,
  Checkbox,
  Divider,
  FormControl,
  FormControlLabel,
  Grid,
  MenuItem,
  Stack,
  TextField,
  Typography,
} from "@mui/material";
import { partySchema, partyTypes } from "../schemas/party.schema";
import type { PartyFormValues } from "../types";
import { useTranslations } from "next-intl";

export function PartyFormMUI({
  defaultValues,
  actionLabel,
  onSubmit,
  error,
}: {
  defaultValues: PartyFormValues;
  actionLabel: string;
  onSubmit: (values: PartyFormValues) => void;
  error?: string | null;
}) {
  const t = useTranslations("parties");
  const common = useTranslations("common");
  const {
    register,
    handleSubmit,
    reset,
    formState: { errors },
  } = useForm<PartyFormValues>({
    resolver: zodResolver(partySchema),
    defaultValues,
  });

  useEffect(() => reset(defaultValues), [defaultValues, reset]);

  return (
    <Card variant="outlined">
      <CardContent sx={{ p: 2.25, "&:last-child": { pb: 2.25 } }}>
        <Stack spacing={2.25}>
          <Stack spacing={0.5}>
            <Typography variant="h6" sx={{ fontWeight: 800 }}>
              {t("details")}
            </Typography>
            <Typography variant="body2" color="text.secondary">
              {t("detailsHint")}
            </Typography>
          </Stack>

          <form onSubmit={handleSubmit(onSubmit)}>
            <Stack spacing={2.25}>
              <Grid container spacing={2}>
                <Grid size={{ xs: 12, md: 6 }}>
                  <TextField
                    label={t("partyCode")}
                    value={defaultValues.code ?? ""}
                    fullWidth
                    disabled
                    helperText={t("autoGenerated")}
                  />
                </Grid>
                <Grid size={{ xs: 12, md: 6 }}>
                  <TextField
                    label={t("arabicName")}
                    fullWidth
                    required
                    error={Boolean(errors.name)}
                    helperText={errors.name?.message}
                    {...register("name")}
                  />
                </Grid>
                <Grid size={{ xs: 12, md: 6 }}>
                  <TextField
                    label={t("englishName")}
                    fullWidth
                    error={Boolean(errors.nameEn)}
                    helperText={errors.nameEn?.message}
                    {...register("nameEn")}
                  />
                </Grid>
                <Grid size={{ xs: 12, md: 6 }}>
                  <TextField
                    select
                    label={t("type")}
                    fullWidth
                    error={Boolean(errors.type)}
                    helperText={errors.type?.message}
                    {...register("type")}
                  >
                    <MenuItem value={partyTypes[0]}>
                      {t("customer")}
                    </MenuItem>
                    <MenuItem value={partyTypes[1]}>
                      {t("supplier")}
                    </MenuItem>
                    <MenuItem value={partyTypes[2]}>{t("both")}</MenuItem>
                  </TextField>
                </Grid>
                <Grid size={{ xs: 12, md: 6 }}>
                  <TextField
                    label={t("mobile")}
                    fullWidth
                    error={Boolean(errors.mobile)}
                    helperText={errors.mobile?.message}
                    {...register("mobile")}
                  />
                </Grid>
                <Grid size={{ xs: 12, md: 6 }}>
                  <TextField
                    label={t("phone")}
                    fullWidth
                    error={Boolean(errors.phone)}
                    helperText={errors.phone?.message}
                    {...register("phone")}
                  />
                </Grid>
                <Grid size={{ xs: 12, md: 6 }}>
                  <TextField
                    label={t("email")}
                    fullWidth
                    error={Boolean(errors.email)}
                    helperText={errors.email?.message}
                    {...register("email")}
                  />
                </Grid>
                <Grid size={{ xs: 12, md: 6 }}>
                  <TextField
                    label={t("city")}
                    fullWidth
                    error={Boolean(errors.city)}
                    helperText={errors.city?.message}
                    {...register("city")}
                  />
                </Grid>
                <Grid size={{ xs: 12, md: 6 }}>
                  <TextField
                    label={t("taxNumber")}
                    fullWidth
                    error={Boolean(errors.taxNumber)}
                    helperText={errors.taxNumber?.message}
                    {...register("taxNumber")}
                  />
                </Grid>
                <Grid size={{ xs: 12, md: 6 }}>
                  <TextField
                    label={t("commercialRegister")}
                    fullWidth
                    error={Boolean(errors.commercialRegister)}
                    helperText={errors.commercialRegister?.message}
                    {...register("commercialRegister")}
                  />
                </Grid>
                <Grid size={{ xs: 12, md: 6 }}>
                  <TextField
                    label={t("openingBalance")}
                    type="number"
                    fullWidth
                    error={Boolean(errors.openingBalance)}
                    helperText={errors.openingBalance?.message}
                    {...register("openingBalance")}
                  />
                </Grid>
                <Grid size={{ xs: 12, md: 6 }}>
                  <FormControl fullWidth>
                    <FormControlLabel
                      control={
                        <Checkbox
                          defaultChecked={defaultValues.isActive}
                          {...register("isActive")}
                        />
                      }
                      label={common("active")}
                    />
                  </FormControl>
                </Grid>
                <Grid size={12}>
                  <TextField
                    label={t("address")}
                    fullWidth
                    error={Boolean(errors.address)}
                    helperText={errors.address?.message}
                    {...register("address")}
                  />
                </Grid>
                <Grid size={12}>
                  <TextField
                    label={t("notes")}
                    fullWidth
                    multiline
                    minRows={4}
                    error={Boolean(errors.notes)}
                    helperText={errors.notes?.message}
                    {...register("notes")}
                  />
                </Grid>
              </Grid>

              {error ? <Alert severity="error">{error}</Alert> : null}

              <Divider />

              <Stack
                direction="row"
                spacing={1}
                sx={{ justifyContent: "flex-end" }}
              >
                <Button type="submit" variant="contained">
                  {actionLabel}
                </Button>
              </Stack>
            </Stack>
          </form>
        </Stack>
      </CardContent>
    </Card>
  );
}
